/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PeliculasDAO;
import Model.Peliculas;

/**
 *
 * @author pipes
 */
public class FrmPelicula extends javax.swing.JFrame {

    /**
     * Creates new form FrmPelicula
     */
    public FrmPelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nombrePeliculajLabel = new javax.swing.JLabel();
        textoPrincipaljLabel = new javax.swing.JLabel();
        anioPeliculajLabel = new javax.swing.JLabel();
        generoPeliculajLabel = new javax.swing.JLabel();
        resumenPeliculajLabel = new javax.swing.JLabel();
        directorPeliculajLabel = new javax.swing.JLabel();
        duracionPeliculajLabel = new javax.swing.JLabel();
        guardarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nombrePeliculajTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        duracionPeliculajTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        anioPeliculajjTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        directorPeliculajTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        generoPeliculajTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        resumenPeliculajTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(187, 187, 187));
        jPanel1.setToolTipText("");

        nombrePeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        nombrePeliculajLabel.setForeground(new java.awt.Color(60, 63, 65));
        nombrePeliculajLabel.setText("Nombre de la pelicula");

        textoPrincipaljLabel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        textoPrincipaljLabel.setForeground(new java.awt.Color(60, 63, 65));
        textoPrincipaljLabel.setText(" Peliculas Premier");

        anioPeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        anioPeliculajLabel.setForeground(new java.awt.Color(60, 63, 65));
        anioPeliculajLabel.setText("Anio de la pelicula");

        generoPeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        generoPeliculajLabel.setForeground(new java.awt.Color(60, 63, 65));
        generoPeliculajLabel.setText("Genero");

        resumenPeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        resumenPeliculajLabel.setForeground(new java.awt.Color(60, 63, 65));
        resumenPeliculajLabel.setText("Resumen");

        directorPeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        directorPeliculajLabel.setForeground(new java.awt.Color(60, 63, 65));
        directorPeliculajLabel.setText("Director de la pelicula");

        duracionPeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        duracionPeliculajLabel.setForeground(new java.awt.Color(60, 63, 65));
        duracionPeliculajLabel.setText("Duracion");

        guardarjButton.setText("Guardar");
        guardarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarjButtonActionPerformed(evt);
            }
        });

        nombrePeliculajTextArea.setColumns(20);
        nombrePeliculajTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        nombrePeliculajTextArea.setRows(5);
        jScrollPane1.setViewportView(nombrePeliculajTextArea);

        duracionPeliculajTextArea.setColumns(20);
        duracionPeliculajTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        duracionPeliculajTextArea.setRows(5);
        jScrollPane2.setViewportView(duracionPeliculajTextArea);

        anioPeliculajjTextArea.setColumns(20);
        anioPeliculajjTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        anioPeliculajjTextArea.setRows(5);
        jScrollPane3.setViewportView(anioPeliculajjTextArea);

        directorPeliculajTextArea.setColumns(20);
        directorPeliculajTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        directorPeliculajTextArea.setRows(5);
        jScrollPane4.setViewportView(directorPeliculajTextArea);

        generoPeliculajTextArea.setColumns(20);
        generoPeliculajTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        generoPeliculajTextArea.setRows(5);
        jScrollPane5.setViewportView(generoPeliculajTextArea);

        resumenPeliculajTextArea.setColumns(20);
        resumenPeliculajTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        resumenPeliculajTextArea.setRows(5);
        jScrollPane6.setViewportView(resumenPeliculajTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(197, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(textoPrincipaljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(356, 356, 356))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(directorPeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(generoPeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombrePeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(duracionPeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resumenPeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(anioPeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(163, 163, 163))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(384, 384, 384)
                .addComponent(guardarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(textoPrincipaljLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombrePeliculajLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anioPeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(directorPeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(generoPeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(duracionPeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resumenPeliculajLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(guardarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarjButtonActionPerformed
        // TODO add your handling code here:
        String titulo = this.nombrePeliculajTextArea.getText();
        int anio = Integer.parseInt(this.anioPeliculajjTextArea.getText());
        String director = this.directorPeliculajTextArea.getText();
        String genero = this.generoPeliculajTextArea.getText();
        int duracion = Integer.parseInt(this.duracionPeliculajTextArea.getText());
        String resumen = this.resumenPeliculajTextArea.getText();
        Peliculas peliculas = new Peliculas(titulo, anio, director, genero, duracion, resumen);
        
        PeliculasDAO peliculasDAO = new PeliculasDAO();
        peliculasDAO.insertarNuevaPelicula(peliculas);
    }//GEN-LAST:event_guardarjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anioPeliculajLabel;
    private javax.swing.JTextArea anioPeliculajjTextArea;
    private javax.swing.JLabel directorPeliculajLabel;
    private javax.swing.JTextArea directorPeliculajTextArea;
    private javax.swing.JLabel duracionPeliculajLabel;
    private javax.swing.JTextArea duracionPeliculajTextArea;
    private javax.swing.JLabel generoPeliculajLabel;
    private javax.swing.JTextArea generoPeliculajTextArea;
    private javax.swing.JButton guardarjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel nombrePeliculajLabel;
    private javax.swing.JTextArea nombrePeliculajTextArea;
    private javax.swing.JLabel resumenPeliculajLabel;
    private javax.swing.JTextArea resumenPeliculajTextArea;
    private javax.swing.JLabel textoPrincipaljLabel;
    // End of variables declaration//GEN-END:variables
}
