/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.PeliculasDAO;
import Model.Peliculas;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/**
 *
 * @author pipes
 */
public class FrmPelicula extends javax.swing.JFrame {

    
    FondoPanel fondoPanel = new FondoPanel();
    
    public FrmPelicula() {
        
        this.setContentPane(fondoPanel);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JPanel jPanel1 = new FondoPanel();
        nombrePeliculajLabel = new javax.swing.JLabel();
        textoPrincipaljLabel = new javax.swing.JLabel();
        anioPeliculajLabel = new javax.swing.JLabel();
        generoPeliculajLabel = new javax.swing.JLabel();
        resumenPeliculajLabel = new javax.swing.JLabel();
        directorPeliculajLabel = new javax.swing.JLabel();
        duracionPeliculajLabel = new javax.swing.JLabel();
        guardarjButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        nombrePeliculajTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        duracionPeliculajTextArea = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        anioPeliculajjTextArea = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        directorPeliculajTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        generoPeliculajTextArea = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        resumenPeliculajTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(187, 187, 187));
        jPanel1.setToolTipText("");
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombrePeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        nombrePeliculajLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombrePeliculajLabel.setText("Nombre de la pelicula");
        jPanel1.add(nombrePeliculajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 203, 42));

        textoPrincipaljLabel.setFont(new java.awt.Font("Dubai Medium", 1, 48)); // NOI18N
        textoPrincipaljLabel.setForeground(new java.awt.Color(0, 0, 0));
        textoPrincipaljLabel.setText(" Peliculas Premier");
        jPanel1.add(textoPrincipaljLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 430, 65));

        anioPeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        anioPeliculajLabel.setForeground(new java.awt.Color(255, 255, 255));
        anioPeliculajLabel.setText("Anio de la pelicula");
        jPanel1.add(anioPeliculajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 203, 34));

        generoPeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        generoPeliculajLabel.setForeground(new java.awt.Color(255, 255, 255));
        generoPeliculajLabel.setText("Genero");
        jPanel1.add(generoPeliculajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 203, 30));

        resumenPeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        resumenPeliculajLabel.setForeground(new java.awt.Color(255, 255, 255));
        resumenPeliculajLabel.setText("Resumen");
        jPanel1.add(resumenPeliculajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 203, 36));

        directorPeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        directorPeliculajLabel.setForeground(new java.awt.Color(255, 255, 255));
        directorPeliculajLabel.setText("Director de la pelicula");
        jPanel1.add(directorPeliculajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 203, 34));

        duracionPeliculajLabel.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        duracionPeliculajLabel.setForeground(new java.awt.Color(255, 255, 255));
        duracionPeliculajLabel.setText("Duracion");
        jPanel1.add(duracionPeliculajLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 360, 203, 34));

        guardarjButton.setText("Guardar");
        guardarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarjButtonActionPerformed(evt);
            }
        });
        jPanel1.add(guardarjButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 131, 42));

        nombrePeliculajTextArea.setBackground(new java.awt.Color(255, 255, 255));
        nombrePeliculajTextArea.setColumns(20);
        nombrePeliculajTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        nombrePeliculajTextArea.setRows(5);
        nombrePeliculajTextArea.setBorder(null);
        nombrePeliculajTextArea.setOpaque(false);
        jScrollPane1.setViewportView(nombrePeliculajTextArea);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 95, 292, 40));

        duracionPeliculajTextArea.setColumns(20);
        duracionPeliculajTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        duracionPeliculajTextArea.setRows(5);
        jScrollPane2.setViewportView(duracionPeliculajTextArea);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 292, 45));

        anioPeliculajjTextArea.setColumns(20);
        anioPeliculajjTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        anioPeliculajjTextArea.setRows(5);
        jScrollPane3.setViewportView(anioPeliculajjTextArea);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 292, 45));

        directorPeliculajTextArea.setColumns(20);
        directorPeliculajTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        directorPeliculajTextArea.setRows(5);
        jScrollPane4.setViewportView(directorPeliculajTextArea);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 292, 45));

        generoPeliculajTextArea.setColumns(20);
        generoPeliculajTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        generoPeliculajTextArea.setRows(5);
        jScrollPane5.setViewportView(generoPeliculajTextArea);

        jPanel1.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 292, 45));

        resumenPeliculajTextArea.setColumns(20);
        resumenPeliculajTextArea.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        resumenPeliculajTextArea.setRows(5);
        jScrollPane6.setViewportView(resumenPeliculajTextArea);

        jPanel1.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 420, 292, 45));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarjButtonActionPerformed
        // TODO add your handling code here:
        String titulo = this.nombrePeliculajTextArea.getText();
        int anio = Integer.parseInt(this.anioPeliculajjTextArea.getText());
        String director = this.directorPeliculajTextArea.getText();
        String genero = this.generoPeliculajTextArea.getText();
        int duracion = Integer.parseInt(this.duracionPeliculajTextArea.getText());
        String resumen = this.resumenPeliculajTextArea.getText();
        Peliculas peliculas = new Peliculas(titulo, anio, director, genero, duracion, resumen);
        
        PeliculasDAO peliculasDAO = new PeliculasDAO();
        peliculasDAO.insertarNuevaPelicula(peliculas);
    }//GEN-LAST:event_guardarjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPelicula().setVisible(true);
                
            }
        });
    }
    
    class FondoPanel extends JPanel{
        private Image imagen;
        
        @Override
        public void paint(Graphics g){
            imagen = new ImageIcon(getClass().getResource("/Img/imgFondo.png")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anioPeliculajLabel;
    private javax.swing.JTextArea anioPeliculajjTextArea;
    private javax.swing.JLabel directorPeliculajLabel;
    private javax.swing.JTextArea directorPeliculajTextArea;
    private javax.swing.JLabel duracionPeliculajLabel;
    private javax.swing.JTextArea duracionPeliculajTextArea;
    private javax.swing.JLabel generoPeliculajLabel;
    private javax.swing.JTextArea generoPeliculajTextArea;
    private javax.swing.JButton guardarjButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel nombrePeliculajLabel;
    private javax.swing.JTextArea nombrePeliculajTextArea;
    private javax.swing.JLabel resumenPeliculajLabel;
    private javax.swing.JTextArea resumenPeliculajTextArea;
    private javax.swing.JLabel textoPrincipaljLabel;
    // End of variables declaration//GEN-END:variables
}
